Tentative fix for wrong sequence number errors by not checking for currentBlockID
flow-hydraulics/flow-pds pull request #136
Opened 2021-11-22 20:45 UTC by fkenji

…rrentBlockID

2021-11-22 23:06 UTC, sadief approved these changes

2021-11-23 01:47 UTC, EricLin2004 approved these changes

2021-11-23 10:03 UTC, latenssi commented
Hi @fkenji and thank you for the PR!

One note: this PR alone will not allow multi-instance setup. Also I am curious to why are you preparing this for multi-instance setup? To my knowledge the bottleneck is the transaction handling on-chain and adding more instances shouldn't help.

2021-11-23 10:03 UTC, latenssi requested changes

2021-11-24 09:32 UTC, latenssi commented
Closing as this was included in PR #138

2021-11-24 09:32 UTC, closed without merging