Add batch loading sent
flow-hydraulics/flow-pds pull request #146
Opened 2022-02-10 00:54 UTC by judezhu

2022-02-11 17:53 UTC, sadief approved these changes

2022-02-28 07:29 UTC, latenssi requested changes

2022-02-28 07:29 UTC, latenssi commented on .github/workflows/build.yml
> +            ghcr.io/dapperlabs/flow-pds
In order to merge this PR, this should be reverted

2022-02-28 07:29 UTC, latenssi commented on test_lib.go
> +	cfg.DatabaseDSN = "postgresql://pds:pds@localhost:5432/pds"
I think this is a bit risky. The test DB should be separated from the actual DB by clearly naming it as a test DB IMO.

2022-05-30 18:18 UTC, judezhu commented
we were working on a fork repo. will port over the changes later. close this one for now.

2022-05-30 18:18 UTC, closed without merging