Add basic API endpoints, functionality not implemented
flow-hydraulics/flow-pds pull request #17
Opened 2021-09-07 11:22 UTC by latenssi

- Add project boilerplate (docker-compose setup, makefile, configs etc.)
- Add initial API endpoints

2021-09-07 14:34 UTC, aphelionz commented
@nanuuki might you be able to give this a once over?

2021-09-08 06:24 UTC, nanuuki requested changes

2021-09-08 06:24 UTC, nanuuki commented on service/http/handlers.go
> +		var dist CreatDistributionRequest
typo
```suggestion
		var dist CreateDistributionRequest
```

2021-09-08 06:24 UTC, nanuuki commented on service/http/types.go
> +type CreatDistributionRequest struct {
typo
```suggestion
type CreateDistributionRequest struct {
```

2021-09-08 06:24 UTC, nanuuki commented on service/http/types.go
> +func (d *CreatDistributionRequest) ToApp() app.Distribution {
typo
```suggestion
func (d *CreateDistributionRequest) ToApp() app.Distribution {
```

2021-09-08 06:29 UTC, nanuuki approved these changes

2021-09-08 06:29 UTC, merged